version: "3.7"

services:

  node:
    image: "node:current-alpine"
    user: "node"
    working_dir: /home/node/app
    depends_on:
     - mongo
    environment:
      NODE_ENV: $NODE_ENV
    volumes:
      - ./:/home/node/app
    ports:
      - "8080:3000"
    command: ["sh", "server-init.sh"]

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./.docker/mongo:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
      MONGO_LOCAL_USERNAME: $MONGO_LOCAL_USERNAME
      MONGO_LOCAL_PASSWORD: $MONGO_LOCAL_PASSWORD
      MONGO_LOCAL_DATABASE: $MONGO_LOCAL_DATABASE

  mongo-express:
    image: "mongo-express"
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_ROOT_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_ROOT_PASSWORD